# Generated by Django 4.1.3 on 2022-11-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_compra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='user',
        ),
    ]
